/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy brand colors
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          500: '#0284c7',
          600: '#0369a1',
          700: '#075985',
          900: '#0c4a6e',
        },
        // RecoverAI Cinematic Design System
        'surface-container-lowest': '#080d1d',
        'surface-container-highest': '#2f3446',
        'surface-variant': '#2f3446',
        'primary-fixed-dim': '#c1c1ff',
        'surface-container': '#1a1f30',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#422d00',
        'on-primary': '#1400a8',
        'outline': '#908fa1',
        'on-surface': '#dee1f9',
        'on-surface-variant': '#c7c4d8',
        'primary-fixed': '#e1dfff',
        'secondary': '#35D39A',
        'inverse-primary': '#4746e4',
        'on-primary-container': '#f8f5ff',
        'primary-container': '#5b5bf7',
        'tertiary-fixed': '#ffdea8',
        'on-secondary-container': '#004529',
        'error-container': '#93000a',
        'primary': '#c1c1ff',
        'background': '#070B17',
        'surface-container-high': '#25293a',
        'surface-bright': '#34394a',
        'outline-variant': '#464555',
        'inverse-on-surface': '#2b3041',
        'on-secondary': '#003920',
        'secondary-fixed': '#35D39A',
        'secondary-fixed-dim': '#35D39A',
        'secondary-container': '#05bd78',
        'on-primary-fixed': '#09006b',
        'on-primary-fixed-variant': '#2c25cc',
        'tertiary-container': '#946900',
        'tertiary-fixed-dim': '#f9bc45',
        'tertiary': '#f9bc45',
        'surface': '#070B17',
        'surface-tint': '#c1c1ff',
        'on-error': '#690005',
        'inverse-surface': '#dee1f9',
        'surface-dim': '#070B17',
        'surface-container-low': '#161b2b',
        'on-background': '#dee1f9',
        'on-tertiary-container': '#fff5e9',
        'on-tertiary-fixed': '#271900',
        'on-secondary-fixed': '#002111',
        'on-secondary-fixed-variant': '#005231',
        'on-tertiary-fixed-variant': '#5e4200',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
      },
      fontFamily: {
        'geist': ['Geist', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'display-hero': ['Geist', 'sans-serif'],
        'display-hero-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-hero-mobile': ['56px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero': ['110px', { lineHeight: '110%', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '120%', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '130%', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '100%', letterSpacing: '0.1em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '160%', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '160%', fontWeight: '400' }],
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1440px',
        'section-gap': '120px',
        'gutter': '24px',
        'unit': '8px',
      },
    },
  },
  plugins: [],
}
