/**
 * RecoverAI — Phase 5: Recovery Decision Engine Policy Configuration
 *
 * Centralized, authoritative thresholds, limits, and rules for the Recovery Decision Engine.
 */

export const POLICY_CONFIG = {
  // Hard Safety Rule Limits
  MAX_RETRY_LIMIT: 3,
  INSUFFICIENT_FUNDS_RETRY_LIMIT: 2,
  MIN_RECOVERY_PROBABILITY_THRESHOLD: 0.20,
  HIGH_RECOVERY_PROBABILITY_THRESHOLD: 0.70,
  UNKNOWN_DIAGNOSIS_CONFIDENCE_THRESHOLD: 0.60,

  // Economic Prioritization Thresholds (in INR)
  HIGH_VALUE_THRESHOLD: 10000,
  MEDIUM_VALUE_THRESHOLD: 2500,

  // Confidence Bounds for Deterministic Rules
  CONFIDENCE: {
    HARD_GUARDRAIL: 0.98,
    RULE_BASED_HIGH: 0.90,
    RULE_BASED_MODERATE: 0.75,
    CONFLICT_OR_FALLBACK: 0.60,
  },

  // Rule Identifiers for Explainability & Auditability
  RULES: {
    MAX_RETRY_LIMIT_EXCEEDED: 'MAX_RETRY_LIMIT_EXCEEDED',
    EXPIRED_PAYMENT_INSTRUMENT: 'EXPIRED_PAYMENT_INSTRUMENT',
    REPEATED_INSUFFICIENT_FUNDS: 'REPEATED_INSUFFICIENT_FUNDS',
    VERY_LOW_RECOVERY_PROBABILITY: 'VERY_LOW_RECOVERY_PROBABILITY',
    TEMPORARY_FAILURE_RETRY_POLICY: 'TEMPORARY_FAILURE_RETRY_POLICY',
    CUSTOMER_AUTHENTICATION_REQUIRED: 'CUSTOMER_AUTHENTICATION_REQUIRED',
    TRANSIENT_WAIT_WINDOW_POLICY: 'TRANSIENT_WAIT_WINDOW_POLICY',
    UNKNOWN_FAILURE_ESCALATION: 'UNKNOWN_FAILURE_ESCALATION',
    CONFLICTING_SIGNALS_POLICY: 'CONFLICTING_SIGNALS_POLICY',
    HIGH_VALUE_TRANSACTION_REVIEW: 'HIGH_VALUE_TRANSACTION_REVIEW',
    FALLBACK_WAIT_POLICY: 'FALLBACK_WAIT_POLICY',
    LLM_ADVISORY_ACCEPTED: 'LLM_ADVISORY_ACCEPTED',
    LLM_ADVISORY_OVERRIDDEN: 'LLM_ADVISORY_OVERRIDDEN',
  },
} as const;
